version: '3'
services:
  socket_checker:
    image: socket-checker
    environment:
      SOCKET_CHECKER_SECRET: insert-secret-key-here
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - 4045:4045
