version: '3'
services:
  socket-checker:
    build: .
    image: socket-checker
    environment:
      SOCKET_CHECKER_SECRET: test-key-123
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn api:app --reload --host 0.0.0.0 --port 4047
    ports:
      - 4045:4047
